#!/bin/sh

RED="\033[0;31m"
END_COLOR="\033[0m"

echo
echo "Begin pre-commit hook..."

make lint-commit COMMIT_MSG_FILE=$1

exitCode=$?
if [ $exitCode -ne 0 ]; then
    echo
    echo "${RED}Commit lint failed. Please update your commit message format. ${END_COLOR}"
    echo "Example commit messages:"
    echo "  feat(scope): add your feature description here"
    echo "  fix(scope): add your fix description here"
    echo "  chore(scope): add your chore description here"
    echo "  docs(scope): add your docs description here"
    echo "  refactor(scope): add your refactor description here"
    echo "  tests(scope): add your tests description here"
    echo
fi

exit $exitCode
