project_name: newrelic-cli

before:
  hooks:
    - go mod download

builds:
  - id: newrelic
    dir: cmd/newrelic
    binary: newrelic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.appName={{.Binary}}
        -X github.com/newrelic/newrelic-cli/internal/cli.version={{.Version}}

release:
  name_template: "{{.ProjectName}} v{{.Version}}"

archives:
  - id: "default"
    builds:
      - newrelic
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md

signs:
  - artifacts: all
    signature: "${artifact}.sig"
    args: ["--detach-sign", "--u", "92ADA76A30A3F1FD", "${artifact}"]

dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - "newrelic/cli:{{ .Tag }}-amd64"
      - "newrelic/cli:v{{ .Major }}.{{ .Minor }}-amd64"
      - "newrelic/cli:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=repository=http://github.com/newrelic/newrelic-cli"
      - "--label=homepage=https://developer.newrelic.com/"
      - "--label=maintainer=Developer Toolkit <opensource@newrelic.com>"
      - "--platform=linux/amd64"

  - dockerfile: build/package/Dockerfile
    image_templates:
      - "newrelic/cli:{{ .Tag }}-arm64"
      - "newrelic/cli:v{{ .Major }}.{{ .Minor }}-arm64"
      - "newrelic/cli:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=repository=http://github.com/newrelic/newrelic-cli"
      - "--label=homepage=https://developer.newrelic.com/"
      - "--label=maintainer=Developer Toolkit <opensource@newrelic.com>"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "newrelic/cli:{{ .Tag }}"
    image_templates:
      - "newrelic/cli:{{ .Tag }}-amd64"
      - "newrelic/cli:{{ .Tag }}-arm64"

changelog:
  skip: false

nfpms:
  - id: newrelic
    package_name: newrelic-cli
    builds:
      - newrelic
    vendor: New Relic
    homepage: https://github.com/newrelic/newrelic-cli
    maintainer: opensource@newrelic.com
    description: |
      The New Relic CLI is an officially supported command line interface for New Relic, released as part of the Developer Toolkit.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
