project_name: newrelic-cli

before:
  hooks:
    - go mod download

builds:
  - id: newrelic
    dir: cmd/newrelic
    binary: newrelic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore: # go-ole is currently 32-bit only.  Remove this when support is added
      - goos: windows
        goarch: arm
        goarm: 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.appName={{.Binary}}
        -X github.com/newrelic/newrelic-cli/internal/client.version={{.Version}}

release:
  name_template: "{{.ProjectName}} v{{.Version}}"

archives:
  - id: "default"
    builds:
      - newrelic
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md

signs:
  - artifacts: all
    args:
      [
        "-u",
        "0xDC9FC6B1FCE47986",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

# Already using git-chglog
changelog:
  skip: true

blobs:
  -
    provider: s3
    bucket: newrelic-install
    region: us-west-2