---
# Log level for running tutone
# Default: info
log_level: debug

# File to store a copy of the schema
# Default: schema.json
cache:
  schema_file: schema.json

# GraphQL endpoint to query for schema
# Required
endpoint: https://api.newrelic.com/graphql

# How to authenticate to the API
auth:
  header: Api-Key
  api_key_env_var: NEW_RELIC_API_KEY

packages:
  - name: apiaccess
    path: internal/apiaccess
    fileName: command.go
    generators:
      - command
    imports: [] # optional - use for aliasing imports
    commands:
      - name: apiAccess
        shortDescription: Manage New Relic API access keys # optional override (uses NG as default)
        subcommands:
          - name: apiAccessGetKey
            path: ['actor', 'apiAccess', 'key']
            clientPackageName: apiaccess
            clientMethod: nrClient.APIAccess.GetAPIAccessKey
          - name: apiAccessCreateKeys
            clientPackageName: apiaccess
            clientMethod: nrClient.APIAccess.CreateAPIAccessKeys
          - name: apiAccessUpdateKeys
            clientPackageName: apiaccess
            clientMethod: nrClient.APIAccess.UpdateAPIAccessKeys
          - name: apiAccessDeleteKeys
            clientPackageName: apiaccess
            clientMethod: nrClient.APIAccess.DeleteAPIAccessKey
  - name: types
    path: internal/install/types
    generators:
      - typegen
    types:
      - name: OpenInstallationRecipe
        struct_tags: [json, yaml]
      - name: ID
        field_type_override: string
        skip_type_create: true
      - name: OpenInstallationRecipeInputVariable
        struct_tags: [json, yaml]
      - name: OpenInstallationRecipeInstallTarget
        struct_tags: [json, yaml]
      - name: OpenInstallationSuccessLinkConfig
        struct_tags: [json, yaml]
      - name: OpenInstallationQuickstartsFilter
        struct_tags: [json, yaml]
      - name: OpenInstallationAttributes
        struct_tags: [json, yaml]
      - name: OpenInstallationLogMatch
        struct_tags: [json, yaml]
      - name: OpenInstallationPostInstallConfiguration
        struct_tags: [json, yaml]
      - name: OpenInstallationPreInstallConfiguration
        struct_tags: [json, yaml]
      - name: OpenInstallationQuickstartEntityType
        struct_tags: [json, yaml]

generators:
  - name: typegen
    fileName: 'types.go'
