// Code generated by counterfeiter. DO NOT EDIT.
package discoveryfakes

import (
	"context"
	"sync"

	"github.com/newrelic/newrelic-cli/internal/install/discovery"
	"github.com/newrelic/newrelic-cli/internal/install/types"
)

type FakeDiscoverer struct {
	DiscoverStub        func(context.Context) (*types.DiscoveryManifest, error)
	discoverMutex       sync.RWMutex
	discoverArgsForCall []struct {
		arg1 context.Context
	}
	discoverReturns struct {
		result1 *types.DiscoveryManifest
		result2 error
	}
	discoverReturnsOnCall map[int]struct {
		result1 *types.DiscoveryManifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDiscoverer) Discover(arg1 context.Context) (*types.DiscoveryManifest, error) {
	fake.discoverMutex.Lock()
	ret, specificReturn := fake.discoverReturnsOnCall[len(fake.discoverArgsForCall)]
	fake.discoverArgsForCall = append(fake.discoverArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DiscoverStub
	fakeReturns := fake.discoverReturns
	fake.recordInvocation("Discover", []interface{}{arg1})
	fake.discoverMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDiscoverer) DiscoverCallCount() int {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return len(fake.discoverArgsForCall)
}

func (fake *FakeDiscoverer) DiscoverCalls(stub func(context.Context) (*types.DiscoveryManifest, error)) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = stub
}

func (fake *FakeDiscoverer) DiscoverArgsForCall(i int) context.Context {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	argsForCall := fake.discoverArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDiscoverer) DiscoverReturns(result1 *types.DiscoveryManifest, result2 error) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = nil
	fake.discoverReturns = struct {
		result1 *types.DiscoveryManifest
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) DiscoverReturnsOnCall(i int, result1 *types.DiscoveryManifest, result2 error) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = nil
	if fake.discoverReturnsOnCall == nil {
		fake.discoverReturnsOnCall = make(map[int]struct {
			result1 *types.DiscoveryManifest
			result2 error
		})
	}
	fake.discoverReturnsOnCall[i] = struct {
		result1 *types.DiscoveryManifest
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDiscoverer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ discovery.Discoverer = new(FakeDiscoverer)
