// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/newrelic/newrelic-cli/internal/install/types"
)

// Discoverer is an autogenerated mock type for the Discoverer type
type Discoverer struct {
	mock.Mock
}

type Discoverer_Expecter struct {
	mock *mock.Mock
}

func (_m *Discoverer) EXPECT() *Discoverer_Expecter {
	return &Discoverer_Expecter{mock: &_m.Mock}
}

// Discover provides a mock function with given fields: _a0
func (_m *Discoverer) Discover(_a0 context.Context) (*types.DiscoveryManifest, error) {
	ret := _m.Called(_a0)

	var r0 *types.DiscoveryManifest
	if rf, ok := ret.Get(0).(func(context.Context) *types.DiscoveryManifest); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.DiscoveryManifest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Discoverer_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type Discoverer_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Discoverer_Expecter) Discover(_a0 interface{}) *Discoverer_Discover_Call {
	return &Discoverer_Discover_Call{Call: _e.mock.On("Discover", _a0)}
}

func (_c *Discoverer_Discover_Call) Run(run func(_a0 context.Context)) *Discoverer_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Discoverer_Discover_Call) Return(_a0 *types.DiscoveryManifest, _a1 error) *Discoverer_Discover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewDiscoverer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiscoverer creates a new instance of Discoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiscoverer(t mockConstructorTestingTNewDiscoverer) *Discoverer {
	mock := &Discoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
