style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/newrelic/newrelic-cli
options:
  commits:
    filters:
      Type:
        - docs
        - feat
        - fix

  commit_groups:
    title_maps:
      docs: Documentation Updates
      feat: Features
      fix: Bug Fixes

  refs:
    actions:
      - Closes
      - Fixes
      - Resolves

  issues:
    prefix:
      - #

  header:
    pattern: "^(\\w*)(?:\\(([\\/\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE
